{% set name = "levenshtein" %}
{% set version = "0.27.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e18b73564cfc846eec94dd13fab6cb006b5d2e0cc56bad1fd7d5585881302e3

build:
  skip: true  # [py<39]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - pip
    - python
    - scikit-build-core >=0.11
    - cython >=3.0.12,<3.1.0
    - wheel
    - setuptools
  run:
    - python
    - rapidfuzz >=3.9.0,<4.0.0

test:
  source_files:
    - tests
  imports:
    - Levenshtein
  requires:
    - python
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/maxbachmann/Levenshtein
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Python extension for computing string edit distances and similarities.
  description: | 
    The Levenshtein Python C extension module contains functions for fast
    computation of Levenshtein distance and string similarity
  dev_url: https://github.com/maxbachmann/Levenshtein
  doc_url: https://rapidfuzz.github.io/Levenshtein

extra:
  recipe-maintainers:
    - maxbachmann
