{% set name = "Levenshtein" %}
{% set version = "0.20.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Levenshtein-{{ version }}.tar.gz
  sha256: 70a8ad5e28bb76d87da1eb3f31de940836596547d6d01317c2289f5b7cd0b0ea

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
  run:
    - python
    - rapidfuzz >=2.0.1,<3.0.0

test:
  imports:
    - Levenshtein
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/Levenshtein
  summary: Python extension for computing string edit distances and similarities.
  license: GPL-2.0-or-later
  license_file: COPYING
  dev_url: https://github.com/maxbachmann/Levenshtein

extra:
  recipe-maintainers:
    - maxbachmann
