{% set name = "Levenshtein" %}
{% set version = "0.27.1" %}
{% set nameLower = "levenshtein" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ nameLower[0] }}/{{ nameLower }}/{{ nameLower }}-{{ version }}.tar.gz
  sha256: 3e18b73564cfc846eec94dd13fab6cb006b5d2e0cc56bad1fd7d5585881302e3

build:
  skip: true  # [py<39]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build-core >=0.11
    - cython >=3.0.12,<3.1.0
    - wheel
    - setuptools
  run:
    - python
    - rapidfuzz >=3.9.0,<4.0.0

test:
  imports:
    - Levenshtein
  requires:
    - python
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/maxbachmann/Levenshtein
  summary: Python extension for computing string edit distances and similarities.
  license: GPL-2.0-or-later
  license_file: COPYING
  dev_url: https://github.com/maxbachmann/Levenshtein

extra:
  recipe-maintainers:
    - maxbachmann
